### ISSUE TITLE
Clearify the install instructions

### ISSUE THREAD

**Issue by ShalokShalom** [schlichtanders/fall-in-love-with-julia#1]
The first line(s) of your installation instructions do lack any info, of which environment you expect us to run them in:

ProjectFolder="$HOME/JuliaProjects"

Is this something I am supposed to add in my command line?
The Julia document?

Considering this is an introduction course, I hope people check the documented from the perspective of a newbie.

**Comment by schlichtanders** [comment]
Thank you for your help. It is recommended to use jupyter's repo2docker utility

I update the README to fix the snippets of the second installation alternative, which indeed contained a small typo.

---------------

I guess your problem is actually something different, hence I also added remarks about using the terminal.
I hope this makes it simpler and not more complicated.

Having more words may also be more confusing, hence please tell me whether the current version is now understandable for you. Or whether you actually meant something different

**Comment by ShalokShalom** [comment]
Ah, so running it in bash. I am not used running code like this in bash, as it seems like no typical bash command. 

Is it simply binding a variable?
Interesting, that this works on the interactive level :)

I use fish, but I can transfer that knowledge myself.

As a feedback: I would recommend calling WSL as such, since that name / abbreviation is established. 

Also, macOS uses zsh by default.
